#!/usr/bin/env python3
"""Generate a C tileType-to-name table from Rogue.h.

The enum is the source of truth. Keeping this small generator in the pinned
source tree prevents the exporter and compiler from carrying a hand-maintained
copy of Brogue's tile IDs.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "src" / "brogue" / "Rogue.h"
OUTPUT = ROOT / "src" / "brogue" / "TileTypeNames.generated.h"


def parse_names() -> list[str]:
    text = HEADER.read_text(encoding="utf-8")
    match = re.search(r"enum tileType\s*\{(?P<body>.*?)\};", text, re.S)
    if not match:
        raise SystemExit("could not locate enum tileType")

    names: list[str] = []
    for line in match.group("body").splitlines():
        line = line.split("//", 1)[0]
        item = re.match(r"\s*([A-Z][A-Z0-9_]*)\s*(?:=\s*\d+)?\s*,", line)
        if not item:
            continue
        name = item.group(1)
        if name == "NUMBER_TILETYPES":
            break
        names.append(name)

    if not names or names[0] != "NOTHING":
        raise SystemExit("unexpected tileType enum")
    return names


def main() -> None:
    names = parse_names()
    rows = [
        "/* Generated by tools/generate_tile_names.py; do not edit manually. */",
        "#ifndef BROGUE_TILE_TYPE_NAMES_GENERATED_H",
        "#define BROGUE_TILE_TYPE_NAMES_GENERATED_H",
        "",
        "static const char *const brogueTileTypeNames[NUMBER_TILETYPES] = {",
    ]
    rows.extend(f'    [{index}] = "{name}",' for index, name in enumerate(names))
    rows.extend(["};", "", "#endif", ""])
    OUTPUT.write_text("\n".join(rows), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
