version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, maintenance]
  - package-ecosystem: nuget
    directory: /tools/BrogueDoomLauncher
    schedule:
      interval: monthly
    labels: [dependencies, maintenance]
