"""Original CC-BY-SA-4.0 device viewmodels; generic shapes reveal no effect kind."""
import json
from tools.weapon_models.viewmodel import build_parts, tube, md3_bytes, obj_text


def device_parts(staff, frame=0):
    length = 39 if staff else 20
    material = 'wood' if staff else 'brass'
    parts = [tube('device shaft', [(0,0,-20 if staff else -4,1.05),
                                  (0,0,6,1.05),(0,0,length,.55)], material, 12)]
    for z in (-3,0,3,6,length-3):
        parts.append(tube('binding '+str(z), [(0,0,z,1.18),(0,0,z+.7,1.18)], 'grip' if z<7 else 'brass', 12))
    # A brief forward gesture and recovery, independent of simulation timing.
    motion = (0,-1,-2,1,4,3,2,1,0)[frame]
    pose = ((36+motion,-13,-18),(-10,48+motion*2,-9))
    return build_parts(0, frame, held_parts=parts, pose=pose)


def generate(root):
    directory = root/'mod/BrogueDoom/models/devices'
    directory.mkdir(parents=True, exist_ok=True)
    zs, definitions, sprites, records = [], [], [], []
    for staff, name, sprite in ((True,'Staff','BDST'),(False,'Wand','BDWA')):
        frames = [device_parts(staff,i) for i in range(9)]
        filename = name.lower()
        (directory/(filename+'.md3')).write_bytes(md3_bytes(frames))
        (directory/(filename+'.obj')).write_text(obj_text(frames[0]),encoding='ascii')
        cls = 'BrogueView'+name
        zs.extend([f'class {cls} : BrogueVisualWeaponBase', '{ States {',
            'Spawn: TNT1 A -1; Stop;', f'Select: {sprite} A 1 A_Raise; Loop;',
            f'Deselect: {sprite} A 1 A_Lower; Loop;',
            f'Ready: {sprite} A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH); Loop;',
            f'Fire: {sprite} A 1; Goto Ready;', 'BridgeUse:',
            *[f'{sprite} {chr(65+i)} 2;' for i in range(9)], 'Goto Ready; } }'])
        definitions.extend([f'Model {cls}', '{', 'Path "models/devices"',
            f'Model 0 "{filename}.md3"', 'Skin 0 "graphics/BRGHANDS.png"',
            'Scale 1 1 1', 'ScaleWeaponFOV',
            *[f'FrameIndex {sprite} {chr(65+i)} 0 {i}' for i in range(9)], '}'])
        for i in range(9):
            sprites.append(f'Sprite "{sprite}{chr(65+i)}0", 96, 96\n{{ Offset 48, 88\n Patch "BRGITEMS", 0, 0\n}}')
        records.append({'name':name, 'class':cls, 'model':filename+'.md3', 'frames':9,
                        'source':'tools/weapon_models/devices.py', 'license':'CC-BY-SA-4.0'})
    (directory/'MODELDEF.txt').write_text('\n'.join(definitions)+'\n',encoding='ascii')
    (root/'mod/BrogueDoom/brogue_devices.zs').write_text('// Generated by tools/weapon_models/devices.py\n'+'\n'.join(zs)+'\n',encoding='ascii')
    (root/'assets/weapons/brogue_device_registry.json').write_text(json.dumps(records,indent=2)+'\n',encoding='ascii')
    textures=root/'mod/BrogueDoom/TEXTURES.txt'
    existing=textures.read_text(encoding='utf-8')
    begin,end='// BEGIN GENERATED DEVICE PSPRITES','// END GENERATED DEVICE PSPRITES'
    block=begin+'\n'+'\n'.join(sprites)+'\n'+end
    if begin in existing:
        existing=existing[:existing.index(begin)]+block+existing[existing.index(end)+len(end):]
    else:
        existing=existing.rstrip()+'\n\n'+block+'\n'
    textures.write_text(existing,encoding='utf-8')
