#!/usr/bin/env python3
"""Generate presentation-only first-person models for Brogue's weapon catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.pickup_models.generate import Mesh
from tools.weapon_models.viewmodel import POSE_NAMES, TWO_HANDED, build_parts, atlas_bytes, obj_text, md3_bytes


MODEL_DIR = ROOT / "mod" / "BrogueDoom" / "models" / "weapons"
REGISTRY = ROOT / "assets" / "weapons" / "brogue_weapon_registry.json"
ZSCRIPT = ROOT / "mod" / "BrogueDoom" / "brogue_weapons.zs"
MODELDEF = MODEL_DIR / "MODELDEF.txt"
TEXTURES = ROOT / "mod" / "BrogueDoom" / "TEXTURES.txt"

WEAPONS = (
    ("dagger", "thrust"), ("sword", "slash"), ("broadsword", "heavy"),
    ("whip", "lash"), ("rapier", "thrust"), ("flail", "flail"),
    ("mace", "heavy"), ("war hammer", "heavy"), ("spear", "thrust"),
    ("war pike", "thrust"), ("axe", "sweep"), ("war axe", "sweep"),
    ("dart", "throw"), ("incendiary dart", "throw"), ("javelin", "throw"),
)


def state_lines(sprite: str, family: str) -> list[str]:
    durations = (1,2,2,1,1,2,2,2,1) if family not in ('heavy','sweep') else (1,2,3,2,2,3,3,2,1)
    return [f"        {sprite} {chr(65+i)} {t};" for i,t in enumerate(durations)]


def main() -> None:
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    (ROOT / "mod/BrogueDoom/graphics/BRGHANDS.png").write_bytes(atlas_bytes())
    zscript = [
        "// Generated by tools/weapon_models/generate.py; do not edit by hand.", "",
        "class BrogueVisualWeaponBase : Weapon", "{", "    Default", "    {",
        "        Inventory.PickupMessage \"\";", "        Weapon.SelectionOrder -100;",
        "        Weapon.BobRangeX 0;", "        Weapon.BobRangeY 0;",
        "        +INVENTORY.UNDROPPABLE;", "        +INVENTORY.ALWAYSPICKUP;",
        "        +WEAPON.NOAUTOSWITCHTO;", "    }", "}", "",
        "class BrogueWeaponTargetMarker : Actor",
        "{ Default { Radius 1; Height 1; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BTRG A -1; Stop; } }", "",
        "class BrogueWeaponPathMarker : Actor",
        "{ Default { Radius 1; Height 1; Alpha 0.55; RenderStyle \"Translucent\"; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BPTH A -1; Stop; } }", "",
    ]
    modeldef = ["// Generated by tools/weapon_models/generate.py; do not edit by hand.", ""]
    records = []
    for kind, (name, family) in enumerate(WEAPONS):
        cls = f"BrogueViewWeaponK{kind:02d}"
        sprite = f"BW{kind:02d}"
        filename = f"weapon_{kind:02d}.obj"
        frames = [build_parts(kind, i) for i in range(len(POSE_NAMES))]
        (MODEL_DIR / filename).write_text(obj_text(frames[0]), encoding="ascii")
        animated = filename.replace(".obj", ".md3")
        (MODEL_DIR / animated).write_bytes(md3_bytes(frames))
        zscript.extend([
            f"class {cls} : BrogueVisualWeaponBase", "{", "    States", "    {",
            "    Spawn:", "        TNT1 A -1;", "        Stop;",
            "    Select:", f"        {sprite} A 1 A_Raise;", "        Loop;",
            "    Deselect:", f"        {sprite} A 1 A_Lower;", "        Loop;",
            "    Ready:", f"        {sprite} A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);", "        Loop;",
            # GZDoom requires every Weapon class to declare Fire. This state is
            # deliberately inert; native input is intercepted before Doom can
            # enter it and Brogue remains the only attack authority.
            "    Fire:", f"        {sprite} A 1;", "        Goto Ready;",
            "    BridgeAttack:", *state_lines(sprite, family), "        Goto Ready;",
            "    BridgeThrow:",
            f"        {sprite} A 1;", f"        {sprite} J 2;", f"        {sprite} K 2;",
            f"        {sprite} L 1;", f"        {sprite} M 1;", f"        {sprite} N 2;",
            f"        {sprite} O 2;", f"        {sprite} P 2;",
            "        Goto Ready;", "    }", "}", "",
        ])
        modeldef.extend([
            f"Model {cls}", "{", '    Path "models/weapons"', f'    Model 0 "{animated}"',
            '    Skin 0 "graphics/BRGHANDS.png"', "    Scale 1.0 1.0 1.0",
            "    PitchOffset 0", "    ZOffset 0", "    ScaleWeaponFOV",
            *[f"    FrameIndex {sprite} {chr(65+i)} 0 {i}" for i in range(len(POSE_NAMES))], "}", "",
        ])
        records.append({"kind": kind, "name": name, "class": cls, "model": filename,
                        "animatedModel": animated, "skin": "graphics/BRGHANDS.png",
                        "authoringSource": "assets/weapons/hero-weapons.blend",
                        "animationFamily": family, "frames": list(POSE_NAMES),
                        "grip": "two-handed" if kind in TWO_HANDED else "one-handed",
                        "triangles": sum(len(p.faces) for p in frames[0])})

    # Small floor-plane diamonds used by the authoritative target preview.
    for filename, cls, sprite, size in (
        ("target_marker.obj", "BrogueWeaponTargetMarker", "BTRG", 13),
        ("path_marker.obj", "BrogueWeaponPathMarker", "BPTH", 7),
    ):
        marker = Mesh(cls)
        marker.face([(-size, 0, 0), (0, 0, size), (size, 0, 0), (0, 0, -size)], "gold")
        marker.write(MODEL_DIR / filename)
        modeldef.extend([
            f"Model {cls}", "{", '    Path "models/weapons"', f'    Model 0 "{filename}"',
            '    Skin 0 "graphics/BRGITEMS.png"', "    Scale 1.0 1.0 1.0",
            f"    FrameIndex {sprite} A 0 0", "}", "",
        ])

    REGISTRY.write_text(json.dumps({"schemaVersion": 2, "weaponCount": len(records), "weapons": records}, indent=2) + "\n", encoding="utf-8")
    ZSCRIPT.write_text("\n".join(zscript), encoding="utf-8")
    MODELDEF.write_text("\n".join(modeldef), encoding="utf-8")
    # PSprite rendering still needs a real sprite texture to establish HUD
    # bounds and offsets before MODELDEF substitutes the 3D model.
    begin, end = "// BEGIN GENERATED BROGUE WEAPON PSPRITES", "// END GENERATED BROGUE WEAPON PSPRITES"
    declarations = [begin]
    for kind in range(len(WEAPONS)):
        for frame in range(len(POSE_NAMES)):
            declarations.extend([
                f'Sprite "BW{kind:02d}{chr(65+frame)}0", 96, 96', "{", "    Offset 48, 88",
                '    Patch "BRGITEMS", 0, 0', "}", "",
            ])
    declarations.append(end)
    existing = TEXTURES.read_text(encoding="utf-8")
    if begin in existing:
        a, b = existing.index(begin), existing.index(end) + len(end)
        existing = existing[:a] + "\n".join(declarations) + existing[b:]
    else:
        existing = existing.rstrip() + "\n\n" + "\n".join(declarations) + "\n"
    TEXTURES.write_text(existing, encoding="utf-8")
    from tools.weapon_models.devices import generate
    generate(ROOT)
    print(json.dumps({"weapons": len(records), "registry": str(REGISTRY)}))


if __name__ == "__main__":
    main()
