#!/usr/bin/env python3
"""Generate presentation-only first-person models for Brogue's weapon catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.pickup_models.generate import Mesh


MODEL_DIR = ROOT / "mod" / "BrogueDoom" / "models" / "weapons"
REGISTRY = ROOT / "assets" / "weapons" / "brogue_weapon_registry.json"
ZSCRIPT = ROOT / "mod" / "BrogueDoom" / "brogue_weapons.zs"
MODELDEF = MODEL_DIR / "MODELDEF.txt"
TEXTURES = ROOT / "mod" / "BrogueDoom" / "TEXTURES.txt"

WEAPONS = (
    ("dagger", "thrust"), ("sword", "slash"), ("broadsword", "heavy"),
    ("whip", "lash"), ("rapier", "thrust"), ("flail", "flail"),
    ("mace", "heavy"), ("war hammer", "heavy"), ("spear", "thrust"),
    ("war pike", "thrust"), ("axe", "sweep"), ("war axe", "sweep"),
    ("dart", "throw"), ("incendiary dart", "throw"), ("javelin", "throw"),
)


def build_weapon(kind: int) -> Mesh:
    mesh = Mesh(f"BrogueViewWeaponK{kind:02d}")
    # Both hands and cuffs are part of each viewmodel, avoiding sprite/model
    # layering differences between renderers.
    mesh.sphere(-7, 0, -1, 5.5, "leather", 4, 8)
    mesh.sphere(7, 2, 1, 5.5, "leather", 4, 8)
    mesh.box(-7, -7, -1, 10, 8, 10, "leather")
    mesh.box(7, -5, 1, 10, 8, 10, "leather")
    mesh.box(-7, -1, -1, 11, 2, 11, "gold")
    mesh.box(7, 1, 1, 11, 2, 11, "gold")

    if kind in (0, 1, 2, 4):
        length = (28, 42, 56, 43)[(0, 1, 2, 4).index(kind)]
        width = 3 if kind in (0, 4) else (5 if kind == 1 else 8)
        mesh.box(0, 5, 0, 4, 16, 4, "wood")
        mesh.box(0, 20, 0, 18, 3, 5, "gold")
        mesh.box(0, 21, 0, width, length, 2.5, "metal")
    elif kind == 3:  # whip
        mesh.box(0, 4, 0, 4, 18, 4, "wood")
        for index in range(12):
            mesh.box((index - 4) * 3.0, 20 + index * 2.0, (index % 3 - 1) * 2.0,
                     3.5, 4.0, 2.0, "leather")
    elif kind == 5:  # flail
        mesh.box(0, 5, 0, 5, 28, 5, "wood")
        for index in range(6):
            mesh.box(index * 2.5, 32 + index * 3, 0, 2, 4, 2, "metal")
        mesh.sphere(16, 49, 0, 7, "metal", 5, 10)
    elif kind in (6, 7):
        mesh.box(0, 4, 0, 5, 34 if kind == 6 else 42, 5, "wood")
        if kind == 6:
            mesh.sphere(0, 38, 0, 9, "metal", 5, 10)
        else:
            mesh.box(0, 42, 0, 22, 13, 10, "metal")
    elif kind in (8, 9, 14):
        length = 60 if kind == 8 else (76 if kind == 9 else 48)
        mesh.box(0, 4, 0, 4, length, 4, "wood")
        mesh.box(0, 4 + length, 0, 8, 14, 3, "metal")
    elif kind in (10, 11):
        mesh.box(0, 4, 0, 5, 38 if kind == 10 else 48, 5, "wood")
        head = 20 if kind == 10 else 28
        mesh.box(0, 40 if kind == 10 else 50, 0, head, 16, 4, "metal")
    else:  # darts
        mesh.box(0, 7, 0, 3, 34, 3, "metal")
        mesh.box(0, 41, 0, 8, 12, 2, "metal")
        if kind == 13:
            mesh.box(0, 25, 0, 7, 10, 7, "leather")
            mesh.sphere(0, 30, 0, 3.5, "gold", 3, 8)
    # Mesh primitives use (horizontal, length, depth). GZDoom's model space is
    # X-forward, Y-left, Z-up. Move the HUD model well in front of the near
    # plane; leaving geometry at X=0 causes perspective blow-up regardless of
    # MODELDEF scale.
    mesh.vertices = [(depth + 60.0, length - 25.0, horizontal)
                     for horizontal, length, depth in mesh.vertices]
    return mesh


def state_lines(sprite: str, family: str) -> list[str]:
    if family in ("slash", "sweep", "lash", "flail"):
        angles = (-18, 18, 38 if family == "sweep" else 28, 0)
        return [f"        {sprite} A 1 A_OverlayRotate(PSP_WEAPON, {angle});" for angle in angles]
    if family == "heavy":
        return [
            f"        {sprite} A 2 A_OverlayRotate(PSP_WEAPON, -24);",
            f"        {sprite} A 2 A_OverlayRotate(PSP_WEAPON, 35);",
            f"        {sprite} A 2 A_OverlayRotate(PSP_WEAPON, 0);",
        ]
    return [
        f"        {sprite} A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);",
        f"        {sprite} A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);",
        f"        {sprite} A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);",
    ]


def main() -> None:
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    zscript = [
        "// Generated by tools/weapon_models/generate.py; do not edit by hand.", "",
        "class BrogueVisualWeaponBase : Weapon", "{", "    Default", "    {",
        "        Inventory.PickupMessage \"\";", "        Weapon.SelectionOrder -100;",
        "        +INVENTORY.UNDROPPABLE;", "        +INVENTORY.ALWAYSPICKUP;",
        "        +WEAPON.NOAUTOSWITCHTO;", "    }", "}", "",
        "class BrogueWeaponTargetMarker : Actor",
        "{ Default { Radius 1; Height 1; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BTRG A -1; Stop; } }", "",
        "class BrogueWeaponPathMarker : Actor",
        "{ Default { Radius 1; Height 1; Alpha 0.55; RenderStyle \"Translucent\"; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BPTH A -1; Stop; } }", "",
    ]
    modeldef = ["// Generated by tools/weapon_models/generate.py; do not edit by hand.", ""]
    records = []
    for kind, (name, family) in enumerate(WEAPONS):
        cls = f"BrogueViewWeaponK{kind:02d}"
        sprite = f"BW{kind:02d}"
        filename = f"weapon_{kind:02d}.obj"
        build_weapon(kind).write(MODEL_DIR / filename)
        zscript.extend([
            f"class {cls} : BrogueVisualWeaponBase", "{", "    States", "    {",
            "    Spawn:", "        TNT1 A -1;", "        Stop;",
            "    Select:", f"        {sprite} A 1 A_Raise;", "        Loop;",
            "    Deselect:", f"        {sprite} A 1 A_Lower;", "        Loop;",
            "    Ready:", f"        {sprite} A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);", "        Loop;",
            # GZDoom requires every Weapon class to declare Fire. This state is
            # deliberately inert; native input is intercepted before Doom can
            # enter it and Brogue remains the only attack authority.
            "    Fire:", "        TNT1 A 1;", "        Goto Ready;",
            "    BridgeAttack:", *state_lines(sprite, family), "        Goto Ready;",
            "    BridgeThrow:",
            f"        {sprite} A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);",
            f"        {sprite} A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);",
            f"        {sprite} A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);",
            "        Goto Ready;", "    }", "}", "",
        ])
        modeldef.extend([
            f"Model {cls}", "{", '    Path "models/weapons"', f'    Model 0 "{filename}"',
            '    Skin 0 "graphics/BRGITEMS.png"', "    Scale 1.0 1.0 1.0",
            "    PitchOffset 0", "    ZOffset 0", "    ScaleWeaponFOV",
            f"    FrameIndex {sprite} A 0 0", "}", "",
        ])
        records.append({"kind": kind, "name": name, "class": cls, "model": filename, "animationFamily": family})

    # Small floor-plane diamonds used by the authoritative target preview.
    for filename, cls, sprite, size in (
        ("target_marker.obj", "BrogueWeaponTargetMarker", "BTRG", 13),
        ("path_marker.obj", "BrogueWeaponPathMarker", "BPTH", 7),
    ):
        marker = Mesh(cls)
        marker.face([(-size, 0, 0), (0, 0, size), (size, 0, 0), (0, 0, -size)], "gold")
        marker.write(MODEL_DIR / filename)
        modeldef.extend([
            f"Model {cls}", "{", '    Path "models/weapons"', f'    Model 0 "{filename}"',
            '    Skin 0 "graphics/BRGITEMS.png"', "    Scale 1.0 1.0 1.0",
            f"    FrameIndex {sprite} A 0 0", "}", "",
        ])

    REGISTRY.write_text(json.dumps({"schemaVersion": 1, "weaponCount": len(records), "weapons": records}, indent=2) + "\n", encoding="utf-8")
    ZSCRIPT.write_text("\n".join(zscript), encoding="utf-8")
    MODELDEF.write_text("\n".join(modeldef), encoding="utf-8")
    # PSprite rendering still needs a real sprite texture to establish HUD
    # bounds and offsets before MODELDEF substitutes the 3D model.
    begin, end = "// BEGIN GENERATED BROGUE WEAPON PSPRITES", "// END GENERATED BROGUE WEAPON PSPRITES"
    declarations = [begin]
    for kind in range(len(WEAPONS)):
        declarations.extend([
            f'Sprite "BW{kind:02d}A0", 96, 96', "{", "    Offset 48, 88",
            '    Patch "BRGITEMS", 0, 0', "}", "",
        ])
    declarations.append(end)
    existing = TEXTURES.read_text(encoding="utf-8")
    if begin in existing:
        existing = existing[:existing.index(begin)].rstrip() + "\n"
    TEXTURES.write_text(existing.rstrip() + "\n\n" + "\n".join(declarations) + "\n", encoding="utf-8")
    print(json.dumps({"weapons": len(records), "registry": str(REGISTRY)}))


if __name__ == "__main__":
    main()
