"""Safe replacement of generated viewmodel assets."""

import os
from pathlib import Path
import tempfile


def write_asset(path: Path, payload: bytes) -> bool:
    """Skip identical assets; stage changed bytes before replacing the old file.

    In particular, never truncate an existing model before generation succeeds.
    Replacement errors remain fatal: a build must not package stale assets.
    """
    try:
        if path.read_bytes() == payload:
            return False
    except FileNotFoundError:
        pass
    staged = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, prefix=path.name + ".",
                                         suffix=".tmp", delete=False) as stream:
            staged = Path(stream.name)
            stream.write(payload)
        os.replace(staged, path)
    except OSError as error:
        raise OSError(error.errno,
                      "Could not replace generated asset; check file permissions "
                      "and whether another process is holding it. " + str(error),
                      str(path)) from error
    finally:
        if staged is not None:
            staged.unlink(missing_ok=True)
    return True


def write_asset_text(path: Path, text: str, encoding: str = "ascii") -> bool:
    # Match Path.write_text's native newline convention, preserving existing
    # generated bytes on Windows as well as Unix.
    return write_asset(path, text.replace("\n", os.linesep).encode(encoding))
