// Generated by tools.monster_models.skeletal_registry; do not edit.
#pragma once
struct SkeletalPresentation { const char* actorClass; const char* clips[6]; int durations[6]; int walkFrames; const char* captiveClass; const char* captiveClip; const char* releaseClip; int releaseTics; };
static constexpr SkeletalPresentation SkeletalPresentations[] = {
    {"BrogueMonsterK01", {"idle", "scurry", "bite", "scratch", "recoil", "death"}, {0, 0, 16, 18, 12, 26}, 16, "", "", "", 0},
    {"BrogueMonsterK02", {"idle", "walk", "attack", "attack_alt", "hit", "death"}, {0, 0, 20, 22, 12, 28}, 16, "", "", "", 0},
    {"BrogueMonsterK03", {"idle", "prowl", "bite", "maul", "recoil", "death"}, {0, 0, 20, 24, 12, 28}, 20, "", "", "", 0},
    {"BrogueMonsterK05", {"idle", "walk", "bite", "snatch", "recoil", "death"}, {0, 0, 20, 22, 12, 28}, 20, "BrogueMonsterK05Captive", "captive", "released", 21},
};
