// Generated by tools.terrain_overlays; original CC0 presentation.
inline const char *TerrainOverlayClass(unsigned tile) { switch(tile) {
case TT_LICHEN: return "BrogueOverlayBTLICHN";
case TT_HAY: return "BrogueOverlayBTHAY";
case TT_RED_BLOOD: return "BrogueOverlayBTBLOOD";
case TT_GREEN_BLOOD: return "BrogueOverlayBTGREEN";
case TT_PURPLE_BLOOD: return "BrogueOverlayBTPURPL";
case TT_ACID_SPLATTER: return "BrogueOverlayBTACID";
case TT_VOMIT: return "BrogueOverlayBTVOMIT";
case TT_URINE: return "BrogueOverlayBTURINE";
case TT_WORM_BLOOD: return "BrogueOverlayBTENTRL";
case TT_PUDDLE: return "BrogueOverlayBTPUDDL";
case TT_ECTOPLASM: return "BrogueOverlayBTECTO";
case TT_ASH: return "BrogueOverlayBTASH";
case TT_EMBERS: return "BrogueOverlayBTEMBR";
case TT_MACHINE_GLYPH: case TT_MACHINE_GLYPH_INACTIVE: case TT_SACRED_GLYPH: return "BrogueOverlayBTGLYPH";
case TT_SUNLIGHT_POOL: case TT_PORTAL_LIGHT: return "BrogueOverlayBTSUN";
case TT_DARKNESS_PATCH: return "BrogueOverlayBTSHADE";
case TT_GUARDIAN_GLOW: return "BrogueOverlayBTGLOW";
case TT_MACHINE_COLLAPSE_EDGE_SPREADING: return "BrogueOverlayBTCRUMB";
case TT_HOLE_EDGE: return "BrogueOverlayBTFADE";
default: return ""; } }
inline bool TerrainKeepsSubstrate(unsigned tile) { if (*TerrainOverlayClass(tile)) return true; switch(tile) {
case TT_ALTAR_CAGE_OPEN: case TT_ALTAR_INERT: case TT_ALTAR_KEYHOLE: case TT_ALTAR_SWITCH: case TT_ALTAR_SWITCH_RETRACTING: case TT_ANCIENT_SPIRIT_VINES: case TT_BONES: case TT_BRAZIER: case TT_BRIDGE: case TT_BRIDGE_EDGE: case TT_BRIDGE_FALLING: case TT_BROKEN_GLASS: case TT_COFFIN_CLOSED: case TT_COFFIN_OPEN: case TT_COMMUTATION_ALTAR: case TT_COMMUTATION_ALTAR_INERT: case TT_DEEP_WATER_ALGAE_1: case TT_DEEP_WATER_ALGAE_2: case TT_DEWAR_CAUSTIC_GAS: case TT_DEWAR_CONFUSION_GAS: case TT_DEWAR_METHANE_GAS: case TT_DEWAR_PARALYSIS_GAS: case TT_DUNGEON_PORTAL: case TT_ELECTRIC_CRYSTAL_OFF: case TT_ELECTRIC_CRYSTAL_ON: case TT_FUNGUS_FOREST: case TT_GRAY_FUNGUS: case TT_HAVEN_BEDROLL: case TT_JUNK: case TT_LOCKED_DOOR: case TT_MONSTER_CAGE_OPEN: case TT_MUD_DOORWAY: case TT_NETTING: case TT_OPEN_IRON_DOOR_INERT: case TT_PEDESTAL: case TT_PILOT_LIGHT: case TT_PIPE_GLOWING: case TT_PIPE_INERT: case TT_PORTAL: case TT_RESURRECTION_ALTAR: case TT_RESURRECTION_ALTAR_INERT: case TT_RUBBLE: case TT_SACRIFICE_ALTAR: case TT_SACRIFICE_ALTAR_DORMANT: case TT_SPIDERWEB: case TT_TRAMPLED_FOLIAGE: case TT_TRAMPLED_FUNGUS_FOREST: case TT_UNICORN_POOP: return true; default: return false; } }
