// Generated by tools/monster_models/generate.py; do not edit by hand.

class BrogueMonsterProxyBase : Actor
{
    Default
    {
        Radius 1; Height 1; Scale 1.0;
        +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; +NOTONAUTOMAP;
    }
    States { Spawn: BRM0 A -1; Stop; }
}

class BrogueMonsterK00 : BrogueMonsterProxyBase {}
class BrogueMonsterK01 : BrogueMonsterProxyBase
{
    Default { +DECOUPLEDANIMATIONS; }
    States { Spawn: BRM0 A 0; BRM0 A -1 A_SetAnimation("idle", -1, -1, -1, -1, 1, SAF_LOOP); Stop; }
}
class BrogueMonsterK02 : BrogueMonsterProxyBase {}
class BrogueMonsterK03 : BrogueMonsterProxyBase {}
class BrogueMonsterK04 : BrogueMonsterProxyBase {}
class BrogueMonsterK05 : BrogueMonsterProxyBase {}
class BrogueMonsterK06 : BrogueMonsterProxyBase {}
class BrogueMonsterK07 : BrogueMonsterProxyBase {}
class BrogueMonsterK08 : BrogueMonsterProxyBase {}
class BrogueMonsterK09 : BrogueMonsterProxyBase {}
class BrogueMonsterK10 : BrogueMonsterProxyBase {}
class BrogueMonsterK11 : BrogueMonsterProxyBase {}
class BrogueMonsterK12 : BrogueMonsterProxyBase {}
class BrogueMonsterK13 : BrogueMonsterProxyBase {}
class BrogueMonsterK14 : BrogueMonsterProxyBase {}
class BrogueMonsterK15 : BrogueMonsterProxyBase {}
class BrogueMonsterK16 : BrogueMonsterProxyBase {}
class BrogueMonsterK17 : BrogueMonsterProxyBase {}
class BrogueMonsterK18 : BrogueMonsterProxyBase {}
class BrogueMonsterK19 : BrogueMonsterProxyBase {}
class BrogueMonsterK20 : BrogueMonsterProxyBase {}
class BrogueMonsterK21 : BrogueMonsterProxyBase {}
class BrogueMonsterK22 : BrogueMonsterProxyBase {}
class BrogueMonsterK23 : BrogueMonsterProxyBase {}
class BrogueMonsterK24 : BrogueMonsterProxyBase {}
class BrogueMonsterK25 : BrogueMonsterProxyBase {}
class BrogueMonsterK26 : BrogueMonsterProxyBase {}
class BrogueMonsterK27 : BrogueMonsterProxyBase {}
class BrogueMonsterK28 : BrogueMonsterProxyBase {}
class BrogueMonsterK29 : BrogueMonsterProxyBase {}
class BrogueMonsterK30 : BrogueMonsterProxyBase {}
class BrogueMonsterK31 : BrogueMonsterProxyBase {}
class BrogueMonsterK32 : BrogueMonsterProxyBase {}
class BrogueMonsterK33 : BrogueMonsterProxyBase {}
class BrogueMonsterK34 : BrogueMonsterProxyBase {}
class BrogueMonsterK35 : BrogueMonsterProxyBase {}
class BrogueMonsterK36 : BrogueMonsterProxyBase {}
class BrogueMonsterK37 : BrogueMonsterProxyBase {}
class BrogueMonsterK38 : BrogueMonsterProxyBase {}
class BrogueMonsterK39 : BrogueMonsterProxyBase {}
class BrogueMonsterK40 : BrogueMonsterProxyBase {}
class BrogueMonsterK41 : BrogueMonsterProxyBase {}
class BrogueMonsterK42 : BrogueMonsterProxyBase {}
class BrogueMonsterK43 : BrogueMonsterProxyBase {}
class BrogueMonsterK44 : BrogueMonsterProxyBase {}
class BrogueMonsterK45 : BrogueMonsterProxyBase {}
class BrogueMonsterK46 : BrogueMonsterProxyBase {}
class BrogueMonsterK47 : BrogueMonsterProxyBase {}
class BrogueMonsterK48 : BrogueMonsterProxyBase {}
class BrogueMonsterK49 : BrogueMonsterProxyBase {}
class BrogueMonsterK50 : BrogueMonsterProxyBase {}
class BrogueMonsterK51 : BrogueMonsterProxyBase {}
class BrogueMonsterK52 : BrogueMonsterProxyBase {}
class BrogueMonsterK53 : BrogueMonsterProxyBase {}
class BrogueMonsterK54 : BrogueMonsterProxyBase {}
class BrogueMonsterK55 : BrogueMonsterProxyBase {}
class BrogueMonsterK56 : BrogueMonsterProxyBase {}
class BrogueMonsterK57 : BrogueMonsterProxyBase {}
class BrogueMonsterK58 : BrogueMonsterProxyBase {}
class BrogueMonsterK59 : BrogueMonsterProxyBase {}
class BrogueMonsterK60 : BrogueMonsterProxyBase {}
class BrogueMonsterK61 : BrogueMonsterProxyBase {}
class BrogueMonsterK62 : BrogueMonsterProxyBase {}
class BrogueMonsterK63 : BrogueMonsterProxyBase {}
class BrogueMonsterK64 : BrogueMonsterProxyBase {}
class BrogueMonsterK65 : BrogueMonsterProxyBase {}
class BrogueMonsterK66 : BrogueMonsterProxyBase {}
class BrogueMonsterK67 : BrogueMonsterProxyBase {}
