// Generated by tools/pickup_models/generate.py; do not edit by hand.

class BroguePickupProxyBase : Actor
{
    Default
    {
        Radius 1; Height 1; Scale 1.0;
        +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; +NOTONAUTOMAP;
    }
    States { Spawn: ITM0 A -1; Stop; }
}

class BroguePickupC0001K00 : BroguePickupProxyBase {}

class BroguePickupC0001K01 : BroguePickupProxyBase {}

class BroguePickupC0002K00 : BroguePickupProxyBase {}

class BroguePickupC0002K01 : BroguePickupProxyBase {}

class BroguePickupC0002K02 : BroguePickupProxyBase {}

class BroguePickupC0002K03 : BroguePickupProxyBase {}

class BroguePickupC0002K04 : BroguePickupProxyBase {}

class BroguePickupC0002K05 : BroguePickupProxyBase {}

class BroguePickupC0002K06 : BroguePickupProxyBase {}

class BroguePickupC0002K07 : BroguePickupProxyBase {}

class BroguePickupC0002K08 : BroguePickupProxyBase {}

class BroguePickupC0002K09 : BroguePickupProxyBase {}

class BroguePickupC0002K10 : BroguePickupProxyBase {}

class BroguePickupC0002K11 : BroguePickupProxyBase {}

class BroguePickupC0002K12 : BroguePickupProxyBase {}

class BroguePickupC0002K13 : BroguePickupProxyBase {}

class BroguePickupC0002K14 : BroguePickupProxyBase {}

class BroguePickupC0004K00 : BroguePickupProxyBase {}

class BroguePickupC0004K01 : BroguePickupProxyBase {}

class BroguePickupC0004K02 : BroguePickupProxyBase {}

class BroguePickupC0004K03 : BroguePickupProxyBase {}

class BroguePickupC0004K04 : BroguePickupProxyBase {}

class BroguePickupC0004K05 : BroguePickupProxyBase {}

class BroguePickupC0008Generic : BroguePickupProxyBase {}

class BroguePickupC0008K00 : BroguePickupProxyBase {}

class BroguePickupC0008K01 : BroguePickupProxyBase {}

class BroguePickupC0008K02 : BroguePickupProxyBase {}

class BroguePickupC0008K03 : BroguePickupProxyBase {}

class BroguePickupC0008K04 : BroguePickupProxyBase {}

class BroguePickupC0008K05 : BroguePickupProxyBase {}

class BroguePickupC0008K06 : BroguePickupProxyBase {}

class BroguePickupC0008K07 : BroguePickupProxyBase {}

class BroguePickupC0008K08 : BroguePickupProxyBase {}

class BroguePickupC0008K09 : BroguePickupProxyBase {}

class BroguePickupC0008K10 : BroguePickupProxyBase {}

class BroguePickupC0008K11 : BroguePickupProxyBase {}

class BroguePickupC0008K12 : BroguePickupProxyBase {}

class BroguePickupC0008K13 : BroguePickupProxyBase {}

class BroguePickupC0008K14 : BroguePickupProxyBase {}

class BroguePickupC0008K15 : BroguePickupProxyBase {}

class BroguePickupC0016Generic : BroguePickupProxyBase {}

class BroguePickupC0016K00 : BroguePickupProxyBase {}

class BroguePickupC0016K01 : BroguePickupProxyBase {}

class BroguePickupC0016K02 : BroguePickupProxyBase {}

class BroguePickupC0016K03 : BroguePickupProxyBase {}

class BroguePickupC0016K04 : BroguePickupProxyBase {}

class BroguePickupC0016K05 : BroguePickupProxyBase {}

class BroguePickupC0016K06 : BroguePickupProxyBase {}

class BroguePickupC0016K07 : BroguePickupProxyBase {}

class BroguePickupC0016K08 : BroguePickupProxyBase {}

class BroguePickupC0016K09 : BroguePickupProxyBase {}

class BroguePickupC0016K10 : BroguePickupProxyBase {}

class BroguePickupC0016K11 : BroguePickupProxyBase {}

class BroguePickupC0016K12 : BroguePickupProxyBase {}

class BroguePickupC0016K13 : BroguePickupProxyBase {}

class BroguePickupC0032Generic : BroguePickupProxyBase {}

class BroguePickupC0032K00 : BroguePickupProxyBase {}

class BroguePickupC0032K01 : BroguePickupProxyBase {}

class BroguePickupC0032K02 : BroguePickupProxyBase {}

class BroguePickupC0032K03 : BroguePickupProxyBase {}

class BroguePickupC0032K04 : BroguePickupProxyBase {}

class BroguePickupC0032K05 : BroguePickupProxyBase {}

class BroguePickupC0032K06 : BroguePickupProxyBase {}

class BroguePickupC0032K07 : BroguePickupProxyBase {}

class BroguePickupC0032K08 : BroguePickupProxyBase {}

class BroguePickupC0032K09 : BroguePickupProxyBase {}

class BroguePickupC0032K10 : BroguePickupProxyBase {}

class BroguePickupC0032K11 : BroguePickupProxyBase {}

class BroguePickupC0064Generic : BroguePickupProxyBase {}

class BroguePickupC0064K00 : BroguePickupProxyBase {}

class BroguePickupC0064K01 : BroguePickupProxyBase {}

class BroguePickupC0064K02 : BroguePickupProxyBase {}

class BroguePickupC0064K03 : BroguePickupProxyBase {}

class BroguePickupC0064K04 : BroguePickupProxyBase {}

class BroguePickupC0064K05 : BroguePickupProxyBase {}

class BroguePickupC0064K06 : BroguePickupProxyBase {}

class BroguePickupC0064K07 : BroguePickupProxyBase {}

class BroguePickupC0064K08 : BroguePickupProxyBase {}

class BroguePickupC0128Generic : BroguePickupProxyBase {}

class BroguePickupC0128K00 : BroguePickupProxyBase {}

class BroguePickupC0128K01 : BroguePickupProxyBase {}

class BroguePickupC0128K02 : BroguePickupProxyBase {}

class BroguePickupC0128K03 : BroguePickupProxyBase {}

class BroguePickupC0128K04 : BroguePickupProxyBase {}

class BroguePickupC0128K05 : BroguePickupProxyBase {}

class BroguePickupC0128K06 : BroguePickupProxyBase {}

class BroguePickupC0128K07 : BroguePickupProxyBase {}

class BroguePickupC0256K00 : BroguePickupProxyBase {}

class BroguePickupC0256K01 : BroguePickupProxyBase {}

class BroguePickupC0256K02 : BroguePickupProxyBase {}

class BroguePickupC0256K03 : BroguePickupProxyBase {}

class BroguePickupC0256K04 : BroguePickupProxyBase {}

class BroguePickupC0256K05 : BroguePickupProxyBase {}

class BroguePickupC0256K06 : BroguePickupProxyBase {}

class BroguePickupC0256K07 : BroguePickupProxyBase {}

class BroguePickupC0256K08 : BroguePickupProxyBase {}

class BroguePickupC0256K09 : BroguePickupProxyBase {}

class BroguePickupC0256K10 : BroguePickupProxyBase {}

class BroguePickupC0256K11 : BroguePickupProxyBase {}

class BroguePickupC0512K00 : BroguePickupProxyBase {}

class BroguePickupC1024K00 : BroguePickupProxyBase {}

class BroguePickupC2048K00 : BroguePickupProxyBase {}

class BroguePickupC4096K00 : BroguePickupProxyBase {}

class BroguePickupC4096K01 : BroguePickupProxyBase {}

class BroguePickupC4096K02 : BroguePickupProxyBase {}
