class BrogueFlavorStaffteak : BroguePickupProxyBase {}
class BrogueFlavorViewStaffteak : BrogueViewStaff {}
class BrogueFlavorStaffoak : BroguePickupProxyBase {}
class BrogueFlavorViewStaffoak : BrogueViewStaff {}
class BrogueFlavorStaffredwood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffredwood : BrogueViewStaff {}
class BrogueFlavorStaffrowan : BroguePickupProxyBase {}
class BrogueFlavorViewStaffrowan : BrogueViewStaff {}
class BrogueFlavorStaffwillow : BroguePickupProxyBase {}
class BrogueFlavorViewStaffwillow : BrogueViewStaff {}
class BrogueFlavorStaffmahogany : BroguePickupProxyBase {}
class BrogueFlavorViewStaffmahogany : BrogueViewStaff {}
class BrogueFlavorStaffpinewood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffpinewood : BrogueViewStaff {}
class BrogueFlavorStaffmaple : BroguePickupProxyBase {}
class BrogueFlavorViewStaffmaple : BrogueViewStaff {}
class BrogueFlavorStaffbamboo : BroguePickupProxyBase {}
class BrogueFlavorViewStaffbamboo : BrogueViewStaff {}
class BrogueFlavorStaffironwood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffironwood : BrogueViewStaff {}
class BrogueFlavorStaffpearwood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffpearwood : BrogueViewStaff {}
class BrogueFlavorStaffbirch : BroguePickupProxyBase {}
class BrogueFlavorViewStaffbirch : BrogueViewStaff {}
class BrogueFlavorStaffcherry : BroguePickupProxyBase {}
class BrogueFlavorViewStaffcherry : BrogueViewStaff {}
class BrogueFlavorStaffeucalyptus : BroguePickupProxyBase {}
class BrogueFlavorViewStaffeucalyptus : BrogueViewStaff {}
class BrogueFlavorStaffwalnut : BroguePickupProxyBase {}
class BrogueFlavorViewStaffwalnut : BrogueViewStaff {}
class BrogueFlavorStaffcedar : BroguePickupProxyBase {}
class BrogueFlavorViewStaffcedar : BrogueViewStaff {}
class BrogueFlavorStaffrosewood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffrosewood : BrogueViewStaff {}
class BrogueFlavorStaffyew : BroguePickupProxyBase {}
class BrogueFlavorViewStaffyew : BrogueViewStaff {}
class BrogueFlavorStaffsandalwood : BroguePickupProxyBase {}
class BrogueFlavorViewStaffsandalwood : BrogueViewStaff {}
class BrogueFlavorStaffhickory : BroguePickupProxyBase {}
class BrogueFlavorViewStaffhickory : BrogueViewStaff {}
class BrogueFlavorStaffhemlock : BroguePickupProxyBase {}
class BrogueFlavorViewStaffhemlock : BrogueViewStaff {}
class BrogueFlavorWandbronze : BroguePickupProxyBase {}
class BrogueFlavorViewWandbronze : BrogueViewWand {}
class BrogueFlavorWandsteel : BroguePickupProxyBase {}
class BrogueFlavorViewWandsteel : BrogueViewWand {}
class BrogueFlavorWandbrass : BroguePickupProxyBase {}
class BrogueFlavorViewWandbrass : BrogueViewWand {}
class BrogueFlavorWandpewter : BroguePickupProxyBase {}
class BrogueFlavorViewWandpewter : BrogueViewWand {}
class BrogueFlavorWandnickel : BroguePickupProxyBase {}
class BrogueFlavorViewWandnickel : BrogueViewWand {}
class BrogueFlavorWandcopper : BroguePickupProxyBase {}
class BrogueFlavorViewWandcopper : BrogueViewWand {}
class BrogueFlavorWandaluminum : BroguePickupProxyBase {}
class BrogueFlavorViewWandaluminum : BrogueViewWand {}
class BrogueFlavorWandtungsten : BroguePickupProxyBase {}
class BrogueFlavorViewWandtungsten : BrogueViewWand {}
class BrogueFlavorWandtitanium : BroguePickupProxyBase {}
class BrogueFlavorViewWandtitanium : BrogueViewWand {}
class BrogueFlavorWandcobalt : BroguePickupProxyBase {}
class BrogueFlavorViewWandcobalt : BrogueViewWand {}
class BrogueFlavorWandchromium : BroguePickupProxyBase {}
class BrogueFlavorViewWandchromium : BrogueViewWand {}
class BrogueFlavorWandsilver : BroguePickupProxyBase {}
class BrogueFlavorViewWandsilver : BrogueViewWand {}
class BrogueFlavorRingdiamond : BroguePickupProxyBase {}
class BrogueFlavorRingopal : BroguePickupProxyBase {}
class BrogueFlavorRinggarnet : BroguePickupProxyBase {}
class BrogueFlavorRingruby : BroguePickupProxyBase {}
class BrogueFlavorRingamethyst : BroguePickupProxyBase {}
class BrogueFlavorRingtopaz : BroguePickupProxyBase {}
class BrogueFlavorRingonyx : BroguePickupProxyBase {}
class BrogueFlavorRingtourmaline : BroguePickupProxyBase {}
class BrogueFlavorRingsapphire : BroguePickupProxyBase {}
class BrogueFlavorRingobsidian : BroguePickupProxyBase {}
class BrogueFlavorRingmalachite : BroguePickupProxyBase {}
class BrogueFlavorRingaquamarine : BroguePickupProxyBase {}
class BrogueFlavorRingemerald : BroguePickupProxyBase {}
class BrogueFlavorRingjade : BroguePickupProxyBase {}
class BrogueFlavorRingalexandrite : BroguePickupProxyBase {}
class BrogueFlavorRingagate : BroguePickupProxyBase {}
class BrogueFlavorRingbloodstone : BroguePickupProxyBase {}
class BrogueFlavorRingjasper : BroguePickupProxyBase {}
