// Generated by tools/weapon_models/generate.py; do not edit by hand.

class BrogueVisualWeaponBase : Weapon
{
    Default
    {
        Inventory.PickupMessage "";
        Weapon.SelectionOrder -100;
        +INVENTORY.UNDROPPABLE;
        +INVENTORY.ALWAYSPICKUP;
        +WEAPON.NOAUTOSWITCHTO;
    }
}

class BrogueWeaponTargetMarker : Actor
{ Default { Radius 1; Height 1; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BTRG A -1; Stop; } }

class BrogueWeaponPathMarker : Actor
{ Default { Radius 1; Height 1; Alpha 0.55; RenderStyle "Translucent"; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BPTH A -1; Stop; } }

class BrogueViewWeaponK00 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW00 A 1 A_Raise;
        Loop;
    Deselect:
        BW00 A 1 A_Lower;
        Loop;
    Ready:
        BW00 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW00 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW00 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW00 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW00 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW00 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW00 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK01 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW01 A 1 A_Raise;
        Loop;
    Deselect:
        BW01 A 1 A_Lower;
        Loop;
    Ready:
        BW01 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW01 A 1 A_OverlayRotate(PSP_WEAPON, -18);
        BW01 A 1 A_OverlayRotate(PSP_WEAPON, 18);
        BW01 A 1 A_OverlayRotate(PSP_WEAPON, 28);
        BW01 A 1 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW01 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW01 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW01 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK02 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW02 A 1 A_Raise;
        Loop;
    Deselect:
        BW02 A 1 A_Lower;
        Loop;
    Ready:
        BW02 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW02 A 2 A_OverlayRotate(PSP_WEAPON, -24);
        BW02 A 2 A_OverlayRotate(PSP_WEAPON, 35);
        BW02 A 2 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW02 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW02 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW02 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK03 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW03 A 1 A_Raise;
        Loop;
    Deselect:
        BW03 A 1 A_Lower;
        Loop;
    Ready:
        BW03 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW03 A 1 A_OverlayRotate(PSP_WEAPON, -18);
        BW03 A 1 A_OverlayRotate(PSP_WEAPON, 18);
        BW03 A 1 A_OverlayRotate(PSP_WEAPON, 28);
        BW03 A 1 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW03 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW03 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW03 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK04 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW04 A 1 A_Raise;
        Loop;
    Deselect:
        BW04 A 1 A_Lower;
        Loop;
    Ready:
        BW04 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW04 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW04 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW04 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW04 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW04 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW04 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK05 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW05 A 1 A_Raise;
        Loop;
    Deselect:
        BW05 A 1 A_Lower;
        Loop;
    Ready:
        BW05 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW05 A 1 A_OverlayRotate(PSP_WEAPON, -18);
        BW05 A 1 A_OverlayRotate(PSP_WEAPON, 18);
        BW05 A 1 A_OverlayRotate(PSP_WEAPON, 28);
        BW05 A 1 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW05 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW05 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW05 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK06 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW06 A 1 A_Raise;
        Loop;
    Deselect:
        BW06 A 1 A_Lower;
        Loop;
    Ready:
        BW06 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW06 A 2 A_OverlayRotate(PSP_WEAPON, -24);
        BW06 A 2 A_OverlayRotate(PSP_WEAPON, 35);
        BW06 A 2 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW06 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW06 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW06 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK07 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW07 A 1 A_Raise;
        Loop;
    Deselect:
        BW07 A 1 A_Lower;
        Loop;
    Ready:
        BW07 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW07 A 2 A_OverlayRotate(PSP_WEAPON, -24);
        BW07 A 2 A_OverlayRotate(PSP_WEAPON, 35);
        BW07 A 2 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW07 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW07 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW07 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK08 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW08 A 1 A_Raise;
        Loop;
    Deselect:
        BW08 A 1 A_Lower;
        Loop;
    Ready:
        BW08 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW08 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW08 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW08 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW08 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW08 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW08 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK09 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW09 A 1 A_Raise;
        Loop;
    Deselect:
        BW09 A 1 A_Lower;
        Loop;
    Ready:
        BW09 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW09 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW09 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW09 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW09 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW09 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW09 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK10 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW10 A 1 A_Raise;
        Loop;
    Deselect:
        BW10 A 1 A_Lower;
        Loop;
    Ready:
        BW10 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW10 A 1 A_OverlayRotate(PSP_WEAPON, -18);
        BW10 A 1 A_OverlayRotate(PSP_WEAPON, 18);
        BW10 A 1 A_OverlayRotate(PSP_WEAPON, 38);
        BW10 A 1 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW10 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW10 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW10 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK11 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW11 A 1 A_Raise;
        Loop;
    Deselect:
        BW11 A 1 A_Lower;
        Loop;
    Ready:
        BW11 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW11 A 1 A_OverlayRotate(PSP_WEAPON, -18);
        BW11 A 1 A_OverlayRotate(PSP_WEAPON, 18);
        BW11 A 1 A_OverlayRotate(PSP_WEAPON, 38);
        BW11 A 1 A_OverlayRotate(PSP_WEAPON, 0);
        Goto Ready;
    BridgeThrow:
        BW11 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW11 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW11 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK12 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW12 A 1 A_Raise;
        Loop;
    Deselect:
        BW12 A 1 A_Lower;
        Loop;
    Ready:
        BW12 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW12 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW12 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW12 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW12 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW12 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW12 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK13 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW13 A 1 A_Raise;
        Loop;
    Deselect:
        BW13 A 1 A_Lower;
        Loop;
    Ready:
        BW13 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW13 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW13 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW13 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW13 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW13 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW13 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}

class BrogueViewWeaponK14 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW14 A 1 A_Raise;
        Loop;
    Deselect:
        BW14 A 1 A_Lower;
        Loop;
    Ready:
        BW14 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        TNT1 A 1;
        Goto Ready;
    BridgeAttack:
        BW14 A 1 A_OverlayOffset(PSP_WEAPON, 0, 38);
        BW14 A 2 A_OverlayOffset(PSP_WEAPON, 0, 22);
        BW14 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    BridgeThrow:
        BW14 A 2 A_OverlayOffset(PSP_WEAPON, 18, 40);
        BW14 A 2 A_OverlayOffset(PSP_WEAPON, -24, 20);
        BW14 A 1 A_OverlayOffset(PSP_WEAPON, 0, 32);
        Goto Ready;
    }
}
