// Generated by tools/weapon_models/devices.py
class BrogueViewStaff : BrogueVisualWeaponBase
{ States {
Spawn: TNT1 A -1; Stop;
Select: BDST A 1 A_Raise; Loop;
Deselect: BDST A 1 A_Lower; Loop;
Ready: BDST A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH); Loop;
Fire: BDST A 1; Goto Ready;
BridgeUse:
BDST A 2;
BDST B 2;
BDST C 2;
BDST D 2;
BDST E 2;
BDST F 2;
BDST G 2;
BDST H 2;
BDST I 2;
Goto Ready; } }
class BrogueViewWand : BrogueVisualWeaponBase
{ States {
Spawn: TNT1 A -1; Stop;
Select: BDWA A 1 A_Raise; Loop;
Deselect: BDWA A 1 A_Lower; Loop;
Ready: BDWA A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH); Loop;
Fire: BDWA A 1; Goto Ready;
BridgeUse:
BDWA A 2;
BDWA B 2;
BDWA C 2;
BDWA D 2;
BDWA E 2;
BDWA F 2;
BDWA G 2;
BDWA H 2;
BDWA I 2;
Goto Ready; } }
