// Generated by tools/weapon_models/generate.py; do not edit by hand.

class BrogueVisualWeaponBase : Weapon
{
    Default
    {
        Inventory.PickupMessage "";
        Weapon.SelectionOrder -100;
        Weapon.BobRangeX 0;
        Weapon.BobRangeY 0;
        +INVENTORY.UNDROPPABLE;
        +INVENTORY.ALWAYSPICKUP;
        +WEAPON.NOAUTOSWITCHTO;
    }
}

class BrogueWeaponTargetMarker : Actor
{ Default { Radius 1; Height 1; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BTRG A -1; Stop; } }

class BrogueWeaponPathMarker : Actor
{ Default { Radius 1; Height 1; Alpha 0.55; RenderStyle "Translucent"; +NOBLOCKMAP; +NOGRAVITY; +NOINTERACTION; } States { Spawn: BPTH A -1; Stop; } }

class BrogueViewWeaponK00 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW00 A 1 A_Raise;
        Loop;
    Deselect:
        BW00 A 1 A_Lower;
        Loop;
    Ready:
        BW00 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW00 A 1;
        Goto Ready;
    BridgeAttack:
        BW00 A 1;
        BW00 B 2;
        BW00 C 2;
        BW00 D 1;
        BW00 E 1;
        BW00 F 2;
        BW00 G 2;
        BW00 H 2;
        BW00 I 1;
        Goto Ready;
    BridgeThrow:
        BW00 A 1;
        BW00 J 2;
        BW00 K 2;
        BW00 L 1;
        BW00 M 1;
        BW00 N 2;
        BW00 O 2;
        BW00 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK01 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW01 A 1 A_Raise;
        Loop;
    Deselect:
        BW01 A 1 A_Lower;
        Loop;
    Ready:
        BW01 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW01 A 1;
        Goto Ready;
    BridgeAttack:
        BW01 A 1;
        BW01 B 2;
        BW01 C 2;
        BW01 D 1;
        BW01 E 1;
        BW01 F 2;
        BW01 G 2;
        BW01 H 2;
        BW01 I 1;
        Goto Ready;
    BridgeThrow:
        BW01 A 1;
        BW01 J 2;
        BW01 K 2;
        BW01 L 1;
        BW01 M 1;
        BW01 N 2;
        BW01 O 2;
        BW01 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK02 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW02 A 1 A_Raise;
        Loop;
    Deselect:
        BW02 A 1 A_Lower;
        Loop;
    Ready:
        BW02 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW02 A 1;
        Goto Ready;
    BridgeAttack:
        BW02 A 1;
        BW02 B 2;
        BW02 C 3;
        BW02 D 2;
        BW02 E 2;
        BW02 F 3;
        BW02 G 3;
        BW02 H 2;
        BW02 I 1;
        Goto Ready;
    BridgeThrow:
        BW02 A 1;
        BW02 J 2;
        BW02 K 2;
        BW02 L 1;
        BW02 M 1;
        BW02 N 2;
        BW02 O 2;
        BW02 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK03 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW03 A 1 A_Raise;
        Loop;
    Deselect:
        BW03 A 1 A_Lower;
        Loop;
    Ready:
        BW03 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW03 A 1;
        Goto Ready;
    BridgeAttack:
        BW03 A 1;
        BW03 B 2;
        BW03 C 2;
        BW03 D 1;
        BW03 E 1;
        BW03 F 2;
        BW03 G 2;
        BW03 H 2;
        BW03 I 1;
        Goto Ready;
    BridgeThrow:
        BW03 A 1;
        BW03 J 2;
        BW03 K 2;
        BW03 L 1;
        BW03 M 1;
        BW03 N 2;
        BW03 O 2;
        BW03 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK04 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW04 A 1 A_Raise;
        Loop;
    Deselect:
        BW04 A 1 A_Lower;
        Loop;
    Ready:
        BW04 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW04 A 1;
        Goto Ready;
    BridgeAttack:
        BW04 A 1;
        BW04 B 2;
        BW04 C 2;
        BW04 D 1;
        BW04 E 1;
        BW04 F 2;
        BW04 G 2;
        BW04 H 2;
        BW04 I 1;
        Goto Ready;
    BridgeThrow:
        BW04 A 1;
        BW04 J 2;
        BW04 K 2;
        BW04 L 1;
        BW04 M 1;
        BW04 N 2;
        BW04 O 2;
        BW04 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK05 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW05 A 1 A_Raise;
        Loop;
    Deselect:
        BW05 A 1 A_Lower;
        Loop;
    Ready:
        BW05 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW05 A 1;
        Goto Ready;
    BridgeAttack:
        BW05 A 1;
        BW05 B 2;
        BW05 C 2;
        BW05 D 1;
        BW05 E 1;
        BW05 F 2;
        BW05 G 2;
        BW05 H 2;
        BW05 I 1;
        Goto Ready;
    BridgeThrow:
        BW05 A 1;
        BW05 J 2;
        BW05 K 2;
        BW05 L 1;
        BW05 M 1;
        BW05 N 2;
        BW05 O 2;
        BW05 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK06 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW06 A 1 A_Raise;
        Loop;
    Deselect:
        BW06 A 1 A_Lower;
        Loop;
    Ready:
        BW06 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW06 A 1;
        Goto Ready;
    BridgeAttack:
        BW06 A 1;
        BW06 B 2;
        BW06 C 3;
        BW06 D 2;
        BW06 E 2;
        BW06 F 3;
        BW06 G 3;
        BW06 H 2;
        BW06 I 1;
        Goto Ready;
    BridgeThrow:
        BW06 A 1;
        BW06 J 2;
        BW06 K 2;
        BW06 L 1;
        BW06 M 1;
        BW06 N 2;
        BW06 O 2;
        BW06 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK07 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW07 A 1 A_Raise;
        Loop;
    Deselect:
        BW07 A 1 A_Lower;
        Loop;
    Ready:
        BW07 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW07 A 1;
        Goto Ready;
    BridgeAttack:
        BW07 A 1;
        BW07 B 2;
        BW07 C 3;
        BW07 D 2;
        BW07 E 2;
        BW07 F 3;
        BW07 G 3;
        BW07 H 2;
        BW07 I 1;
        Goto Ready;
    BridgeThrow:
        BW07 A 1;
        BW07 J 2;
        BW07 K 2;
        BW07 L 1;
        BW07 M 1;
        BW07 N 2;
        BW07 O 2;
        BW07 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK08 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW08 A 1 A_Raise;
        Loop;
    Deselect:
        BW08 A 1 A_Lower;
        Loop;
    Ready:
        BW08 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW08 A 1;
        Goto Ready;
    BridgeAttack:
        BW08 A 1;
        BW08 B 2;
        BW08 C 2;
        BW08 D 1;
        BW08 E 1;
        BW08 F 2;
        BW08 G 2;
        BW08 H 2;
        BW08 I 1;
        Goto Ready;
    BridgeThrow:
        BW08 A 1;
        BW08 J 2;
        BW08 K 2;
        BW08 L 1;
        BW08 M 1;
        BW08 N 2;
        BW08 O 2;
        BW08 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK09 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW09 A 1 A_Raise;
        Loop;
    Deselect:
        BW09 A 1 A_Lower;
        Loop;
    Ready:
        BW09 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW09 A 1;
        Goto Ready;
    BridgeAttack:
        BW09 A 1;
        BW09 B 2;
        BW09 C 2;
        BW09 D 1;
        BW09 E 1;
        BW09 F 2;
        BW09 G 2;
        BW09 H 2;
        BW09 I 1;
        Goto Ready;
    BridgeThrow:
        BW09 A 1;
        BW09 J 2;
        BW09 K 2;
        BW09 L 1;
        BW09 M 1;
        BW09 N 2;
        BW09 O 2;
        BW09 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK10 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW10 A 1 A_Raise;
        Loop;
    Deselect:
        BW10 A 1 A_Lower;
        Loop;
    Ready:
        BW10 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW10 A 1;
        Goto Ready;
    BridgeAttack:
        BW10 A 1;
        BW10 B 2;
        BW10 C 3;
        BW10 D 2;
        BW10 E 2;
        BW10 F 3;
        BW10 G 3;
        BW10 H 2;
        BW10 I 1;
        Goto Ready;
    BridgeThrow:
        BW10 A 1;
        BW10 J 2;
        BW10 K 2;
        BW10 L 1;
        BW10 M 1;
        BW10 N 2;
        BW10 O 2;
        BW10 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK11 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW11 A 1 A_Raise;
        Loop;
    Deselect:
        BW11 A 1 A_Lower;
        Loop;
    Ready:
        BW11 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW11 A 1;
        Goto Ready;
    BridgeAttack:
        BW11 A 1;
        BW11 B 2;
        BW11 C 3;
        BW11 D 2;
        BW11 E 2;
        BW11 F 3;
        BW11 G 3;
        BW11 H 2;
        BW11 I 1;
        Goto Ready;
    BridgeThrow:
        BW11 A 1;
        BW11 J 2;
        BW11 K 2;
        BW11 L 1;
        BW11 M 1;
        BW11 N 2;
        BW11 O 2;
        BW11 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK12 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW12 A 1 A_Raise;
        Loop;
    Deselect:
        BW12 A 1 A_Lower;
        Loop;
    Ready:
        BW12 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW12 A 1;
        Goto Ready;
    BridgeAttack:
        BW12 A 1;
        BW12 B 2;
        BW12 C 2;
        BW12 D 1;
        BW12 E 1;
        BW12 F 2;
        BW12 G 2;
        BW12 H 2;
        BW12 I 1;
        Goto Ready;
    BridgeThrow:
        BW12 A 1;
        BW12 J 2;
        BW12 K 2;
        BW12 L 1;
        BW12 M 1;
        BW12 N 2;
        BW12 O 2;
        BW12 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK13 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW13 A 1 A_Raise;
        Loop;
    Deselect:
        BW13 A 1 A_Lower;
        Loop;
    Ready:
        BW13 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW13 A 1;
        Goto Ready;
    BridgeAttack:
        BW13 A 1;
        BW13 B 2;
        BW13 C 2;
        BW13 D 1;
        BW13 E 1;
        BW13 F 2;
        BW13 G 2;
        BW13 H 2;
        BW13 I 1;
        Goto Ready;
    BridgeThrow:
        BW13 A 1;
        BW13 J 2;
        BW13 K 2;
        BW13 L 1;
        BW13 M 1;
        BW13 N 2;
        BW13 O 2;
        BW13 P 2;
        Goto Ready;
    }
}

class BrogueViewWeaponK14 : BrogueVisualWeaponBase
{
    States
    {
    Spawn:
        TNT1 A -1;
        Stop;
    Select:
        BW14 A 1 A_Raise;
        Loop;
    Deselect:
        BW14 A 1 A_Lower;
        Loop;
    Ready:
        BW14 A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        Loop;
    Fire:
        BW14 A 1;
        Goto Ready;
    BridgeAttack:
        BW14 A 1;
        BW14 B 2;
        BW14 C 2;
        BW14 D 1;
        BW14 E 1;
        BW14 F 2;
        BW14 G 2;
        BW14 H 2;
        BW14 I 1;
        Goto Ready;
    BridgeThrow:
        BW14 A 1;
        BW14 J 2;
        BW14 K 2;
        BW14 L 1;
        BW14 M 1;
        BW14 N 2;
        BW14 O 2;
        BW14 P 2;
        Goto Ready;
    }
}
