"""Single registry for authored skeletons and generated native clip bindings."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
PATH=ROOT/'assets/monsters/skeletal_profiles.json'
# Creatures still being authored keep their row here (one <SYMBOL>.json each) so
# parallel authoring never edits the shared registry. Generated outputs ignore
# pending rows; `promote` moves a row into PATH at integration time.
PENDING=ROOT/'assets/monsters/skeletal_pending'


def pending_rows():
    return [json.loads(p.read_text()) for p in sorted(PENDING.glob('MK_*.json'))] if PENDING.is_dir() else []


def find(symbol):
    """Registered row for symbol, else its pending authoring row."""
    for row in json.loads(PATH.read_text())['enemies']+pending_rows():
        if row['symbol']==symbol: return row
    raise KeyError(symbol+' has no registered or pending skeletal profile')


def promote(symbol):
    """Append a pending row to the registry, preserving the file's exact format."""
    source=PENDING/(symbol+'.json')
    row=json.loads(source.read_text())
    data=json.loads(PATH.read_text())
    if any(r['symbol']==symbol or r['class']==row['class'] for r in data['enemies']):
        raise ValueError(symbol+' is already registered')
    data['enemies'].append(row)
    PATH.write_bytes((json.dumps(data,indent=2)+'\n').replace('\n','\r\n').encode())
    source.unlink()
    return row


def profiles():
    data=json.loads(PATH.read_text())
    if data['roles']!=['idle','walk','attack','attack_alt','hit','death']:
        raise ValueError('Skeletal role ordering is part of the frontend contract')
    rows=data['enemies']
    if len({r['class'] for r in rows})!=len(rows): raise ValueError('Duplicate skeletal class')
    for row in rows:
        if len(row['clips'])!=6 or len(row['durations'])!=6: raise ValueError('Six roles required')
        manifest=json.loads((ROOT/row['manifest']).read_text())
        clips={c['name']:c for c in manifest['clips']}
        if set(row['clips'])-clips.keys(): raise ValueError('Missing required clip: '+row['class'])
        if clips[row['clips'][1]]['frameCount']!=row['walkFrames']: raise ValueError('Walk length mismatch')
        for i in (0,1):
            if not clips[row['clips'][i]]['loop']: raise ValueError('Locomotion must loop')
        for i in range(2,6):
            if clips[row['clips'][i]]['loop']: raise ValueError('Actions must not loop')
        if 'captivity' in row:
            cap=row['captivity']
            if not clips[cap['idle']]['loop'] or clips[cap['release']]['loop']:
                raise ValueError('Captivity loops; release settles')
            if cap['class'] in {r['class'] for r in rows} or cap['duration'] <= 0:
                raise ValueError('Distinct captive class and positive release duration required')
            if cap['model'] != manifest['variants']['captive']['model']:
                raise ValueError('Captive model mismatch')
    return rows


def native_text(rows=None):
    rows=profiles() if rows is None else rows
    lines=['// Generated by tools.monster_models.skeletal_registry; do not edit.',
           '#pragma once',
           'struct SkeletalPresentation { const char* actorClass; const char* clips[6]; int durations[6]; int walkFrames; const char* captiveClass; const char* captiveClip; const char* releaseClip; int releaseTics; double wallMountBack; };',
           'static constexpr SkeletalPresentation SkeletalPresentations[] = {']
    for row in rows:
        clips=', '.join(json.dumps(n) for n in row['clips'])
        times=', '.join(map(str,row['durations']))
        captivity=row.get('captivity',{})
        extra=', '.join(json.dumps(captivity.get(k,'')) for k in ('class','idle','release'))
        lines.append('    {'+json.dumps(row['class'])+', {'+clips+'}, {'+times+'}, '+str(row['walkFrames'])+', '+extra+', '+str(captivity.get('duration',0))+', '+str(row.get('wallMountBack',0))+'},')
    return '\n'.join(lines+['};',''])


def generate():
    (ROOT/'src/gzdoom-bridge/skeletal_presentation.generated.h').write_text(native_text())


def build():
    import importlib
    # Load the raw rows first: a newly registered enemy has no manifest yet.
    for row in json.loads(PATH.read_text())['enemies']:
        importlib.import_module('tools.monster_models.'+row['module']).build()
    generate()


if __name__=='__main__':
    import sys
    build() if '--build' in sys.argv else generate()
