"""Deterministic shoreline material aliases and 8-bit neighbor data textures.

Original CC0 mask data; existing Project Broom diffuse art stays unchanged.
47 normalized masks share shader programs through extra texture bindings.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
FAMILIES = {
    'E': ('BRGDIRT', 0, 6.0), 'M': ('BRGVEG0', 0, 7.0),
    'F': ('BRGSTONE', 0, 4.0), 'B': ('graphics/BRGBRIDGE.png', 0, 3.0),
    'W': ('BRGWATER', 1, 11.0), 'D': ('BRGWATER', 2, 9.0),
    'S': ('BRGWATER', 1, 11.0), 'T': ('BRGWATER', 2, 9.0),
}

def normalize(mask):
    for i in range(4):
        if mask & ((1 << i) | (1 << ((i+1) % 4))):
            mask &= ~(16 << i)
    return mask

MASKS = sorted({normalize(mask) for mask in range(256)})

def generate(root=ROOT):
    mod = root/'mod/BrogueDoom'
    data = mod/'shaders/shoreline'
    data.mkdir(parents=True, exist_ok=True)
    for mask in MASKS:
        # Binary texels avoid gamma/color-space ambiguity in encoded integers.
        image = Image.new('RGB', (8, 1))
        image.putdata([(255,255,255) if mask & (1<<i) else (0,0,0) for i in range(8)])
        image.save(data/f'mask-{mask:02x}.png', optimize=False)
    textures = '// Generated by tools/shoreline_assets.py; original CC0 mask data.\n'
    materials = '// Shared shaders; masks are texture bindings, not shader permutations.\n'
    for family, (patch, water, width) in FAMILIES.items():
        for mask in MASKS:
            name = f'BS{family}{mask:02X}'
            textures += (f'Flat "{name}", 1254, 1254\n{{\n XScale 9.796875\n YScale 9.796875\n'
                         f' Patch "{patch}", 0, 0\n}}\n')
            materials += (f'material flat {name}\n{{\n shader "shaders/shoreline.fp"\n'
                          f' texture shoreMask "shaders/shoreline/mask-{mask:02x}.png"\n'
                          f' define SHORE_WATER = {water}\n define SHORE_WIDTH = {width:.1f}\n')
            if water:
                materials += ' disablealphatest\n'
                if family in ('S','T'): materials += ' speed 0\n'
            materials += '}\n'
    (data/'textures.txt').write_text(textures, newline='\n')
    (data/'gldefs.txt').write_text(materials, newline='\n')

if __name__ == '__main__': generate()
