"""Shared pinned terrain presentation registry and native lookup generator."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / 'assets/terrain/terrain_presentation.json'
NATIVE = ROOT / 'src/gzdoom-bridge/terrain_presentation.generated.h'
FALLING_VOID_SYMBOLS = {
    'CHASM', 'CHASM_WITH_HIDDEN_BRIDGE', 'CHASM_WITH_HIDDEN_BRIDGE_ACTIVE',
    'HOLE', 'HOLE_GLOW', 'TRAP_DOOR',
}


def symbols():
    text = (ROOT / 'src/brogue-mapgen/src/brogue/Rogue.h').read_text()
    body = text.split('enum tileType {', 1)[1].split('NUMBER_TILETYPES', 1)[0]
    body = re.sub(r'//[^\n]*|/\*.*?\*/', '', body, flags=re.S)
    return [part.strip().split('=')[0].strip() for part in body.split(',') if part.strip()]


def initialize():
    # One-time explicit registry creation. Subsequent generation preserves edits.
    from tools.mapcompiler.compile import PROP_RULES
    vegetation = {'grass': 'BrogueGrassProp', 'fungus': 'BrogueFungusProp',
                  'luminous_fungus': 'BrogueLuminousFungusProp', 'foliage': 'BrogueFoliageProp',
                  'dead_vegetation': 'BrogueDeadVegetationProp'}
    records = {}
    for symbol in symbols():
        material = 'BRGEARTH'
        if 'WATER' in symbol: material = 'BRGWATR'
        elif 'LAVA' in symbol: material = 'BRGMOLT'
        elif symbol in ('MUD', 'MACHINE_MUD_DORMANT'): material = 'BRGSLDG'
        elif 'BRIDGE' in symbol: material = 'BRGBRID'
        elif symbol.startswith('ICE_'): material = 'BRGFLAG'
        # Brogue's CHASM_EDGE and MACHINE_CHASM_EDGE are safe, full-height
        # ground beside a drop. Painting them with the actual void flat makes
        # valid floor polygons read as missing tiles in first person.
        elif symbol in FALLING_VOID_SYMBOLS: material = 'BRGVOID'
        elif any(t in symbol for t in ('GRASS', 'FUNGUS', 'FOLIAGE', 'MOSS')): material = 'BRGMOSS'
        actor = ''
        if symbol in PROP_RULES: actor = vegetation[PROP_RULES[symbol][0]]
        elif symbol in ('DOOR','LOCKED_DOOR','PORTCULLIS_CLOSED','MONSTER_CAGE_CLOSED','ALTAR_CAGE_CLOSED'): actor = 'BrogueDoorMarker'
        elif symbol == 'WOODEN_BARRICADE': actor = 'BrogueBarricadeMarker'
        elif symbol.startswith('WALL_LEVER') and 'HIDDEN' not in symbol: actor = 'BrogueSearchLever'
        elif 'VENT' in symbol and 'HIDDEN' not in symbol: actor = 'BrogueSearchVent'
        elif symbol in ('GAS_TRAP_POISON','GAS_TRAP_CONFUSION','GAS_TRAP_PARALYSIS','MACHINE_PRESSURE_PLATE','MACHINE_PRESSURE_PLATE_USED'): actor = 'BrogueSearchPlate'
        elif symbol == 'FLAMETHROWER': actor = 'BrogueSearchFire'
        elif symbol == 'FLOOD_TRAP': actor = 'BrogueSearchFlood'
        elif symbol == 'NET_TRAP': actor = 'BrogueSearchNet'
        elif symbol == 'ALARM_TRAP': actor = 'BrogueSearchAlarm'
        records[symbol] = dict(floor=material, wall='BRGCAVE', actor=actor,
                               alias='Existing Project Broom material and physical model; specialized artwork deferred.')
    REGISTRY.write_text(json.dumps(records, indent=2) + '\n')


def load():
    records = json.loads(REGISTRY.read_text())
    if set(records) != set(symbols()): raise ValueError('Registry does not cover the pinned terrain catalog exactly')
    return records


def generate():
    records = load()
    text = '// Generated by tools/terrain_presentation.py. Do not edit.\n#pragma once\n'
    text += 'enum TerrainTile { ' + ', '.join('TT_' + symbol for symbol in symbols()) + ' };\n'
    text += 'struct TerrainStyle { const char *floor, *wall, *actor; unsigned motion; };\n'
    text += 'static constexpr TerrainStyle TerrainStyles[] = {\n'
    for symbol in symbols():
        entry = records[symbol]
        text += '    {' + ', '.join(json.dumps(entry[k]) for k in ('floor','wall','actor')) + ', ' + str(entry.get('motion', 0)) + '}, // ' + symbol + '\n'
    text += '};\n'
    NATIVE.write_text(text)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--initialize', action='store_true')
    args = parser.parse_args()
    if args.initialize:
        if REGISTRY.exists(): raise SystemExit('Registry already exists; edit it directly.')
        initialize()
    generate()
