"""Original CC0 masked terrain coatings. No baked substrate or gameplay RNG."""
import math
import random
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
OVERLAYS = {
    'BTBLOOD': 'RED_BLOOD', 'BTGREEN': 'GREEN_BLOOD', 'BTPURPL': 'PURPLE_BLOOD',
    'BTACID': 'ACID_SPLATTER', 'BTVOMIT': 'VOMIT', 'BTURINE': 'URINE',
    'BTENTRL': 'WORM_BLOOD', 'BTPUDDL': 'PUDDLE', 'BTECTO': 'ECTOPLASM',
    'BTASH': 'ASH', 'BTEMBR': 'EMBERS', 'BTLICHN': 'LICHEN', 'BTHAY': 'HAY',
    'BTGLYPH': 'MACHINE_GLYPH MACHINE_GLYPH_INACTIVE SACRED_GLYPH',
    'BTSUN': 'SUNLIGHT_POOL PORTAL_LIGHT', 'BTSHADE': 'DARKNESS_PATCH',
    'BTGLOW': 'GUARDIAN_GLOW', 'BTCRUMB': 'MACHINE_COLLAPSE_EDGE_SPREADING',
    'BTFADE': 'HOLE_EDGE',
}
ADDITIVE = {'BTSUN', 'BTGLOW', 'BTGLYPH', 'BTEMBR', 'BTECTO'}


def coating(identifier, color):
    rng = random.Random(731)
    mask = Image.new('L', (128,128)); d = ImageDraw.Draw(mask)
    if identifier in ('BTSUN', 'BTSHADE', 'BTGLOW'):
        # Soft illumination, with continuous falloff rather than painted islands.
        mask.putdata([int(95 * max(0, 1-((x-64)/58)**2-((y-64)/53)**2)**2)
                      for y in range(128) for x in range(128)])
    elif identifier == 'BTGLYPH':
        d.ellipse((20,20,108,108), outline=200, width=2)
        points=[(64+37*math.cos(i*4*math.pi/5),64+37*math.sin(i*4*math.pi/5)) for i in range(6)]
        d.line(points,fill=210,width=2)
    elif identifier in ('BTCRUMB', 'BTFADE'):
        for i in range(9):
            x,y=rng.randrange(22,106),rng.randrange(22,106)
            d.line([(x,y),(x+7,y+5),(x+2,y+14),(x+9,y+20)], fill=200,width=2 if identifier=='BTCRUMB' else 5)
        color=(9,8,12)
    elif identifier in ('BTHAY', 'BTEMBR', 'BTASH', 'BTLICHN'):
        for i in range(145):
            x,y=rng.randrange(12,116),rng.randrange(12,116)
            if identifier=='BTHAY': d.line((x,y,x+rng.randrange(-9,10),y+rng.randrange(-9,10)),fill=rng.randrange(140,235),width=1)
            else: d.ellipse((x-1,y-1,x+2,y+2),fill=rng.randrange(90,230))
    else:
        for i in range(18):
            x,y=rng.randrange(35,93),rng.randrange(35,93); r=rng.randrange(3,17)
            d.ellipse((x-r,y-r,x+r,y+r),fill=205)
        for i in range(24):
            x,y=rng.randrange(12,116),rng.randrange(12,116)
            d.ellipse((x,y,x+2,y+2),fill=175)
    if identifier not in ('BTHAY','BTGLYPH'): mask=mask.filter(ImageFilter.GaussianBlur(.65))
    image=Image.new('RGBA',(128,128))
    image.putdata([tuple(max(0,min(255,c+rng.randrange(-9,10))) for c in color)+(a,)
                   for a in mask.getdata()])
    return image


def generate():
    from tools.terrain_catalog_assets import SURFACES, OBJECTS
    out=ROOT/'mod/BrogueDoom/models/terrain/catalog'
    graphics=ROOT/'mod/BrogueDoom/graphics'
    # OBJ uses Y up. Both windings keep the coating visible on supported backends.
    (out/'Overlay.obj').write_text('v -31.9 0 -31.9\nv 31.9 0 -31.9\nv 31.9 0 31.9\nv -31.9 0 31.9\nvt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\nf 1/1 4/4 3/3 2/2\nf 2/2 3/3 4/4 1/1\n')
    zs=[]; models=[]; cases=[]
    for identifier,_,color,_ in SURFACES:
        if identifier not in OVERLAYS: continue
        name='BrogueOverlay'+identifier
        coating(identifier,color).save(graphics/(identifier+'O.png'))
        style='Add' if identifier in ADDITIVE else 'Translucent'
        bright=' Bright' if identifier in ADDITIVE else ''
        zs.append(f'class {name} : BrogueTerrainStone {{ Default {{ RenderStyle "{style}"; }} States {{ Spawn: BRGD A -1{bright}; Stop; }} }}')
        models.append(f'Model {name}\n{{\n Path "models/terrain/catalog"\n Model 0 "Overlay.obj"\n Skin 0 "graphics/{identifier}O.png"\n Scale 1 1 1\n FrameIndex BRGD A 0 0\n}}')
        cases.append(' '.join('case TT_'+t+':' for t in OVERLAYS[identifier].split())+f' return "{name}";')
    for path,block in [(out/'MODELDEF.txt','\n'.join(models)),(ROOT/'mod/BrogueDoom/brogue_terrain_catalog.zs','\n'.join(zs))]:
        text=path.read_text().split('// BEGIN TERRAIN OVERLAYS')[0].rstrip()
        path.write_text(text+'\n// BEGIN TERRAIN OVERLAYS\n'+block+'\n')
    props=sorted({t for names in OBJECTS.values() for t in names.split()})
    code='// Generated by tools.terrain_overlays; original CC0 presentation.\n'
    code+='inline const char *TerrainOverlayClass(unsigned tile) { switch(tile) {\n'+'\n'.join(cases)+'\ndefault: return ""; } }\n'
    code+='inline bool TerrainKeepsSubstrate(unsigned tile) { if (*TerrainOverlayClass(tile)) return true; switch(tile) {\n'
    code+=' '.join('case TT_'+t+':' for t in props)+' return true; default: return false; } }\n'
    (ROOT/'src/gzdoom-bridge/terrain_overlays.generated.h').write_text(code)


if __name__=='__main__': generate()
